#!/bin/bash

# Prepare report CSV
CSV_PATH="$PANTIPLIBR/data/report.csv"

if [ ! -f "$CSV_PATH" ] 
then
	touch "$CSV_PATH"
else
	rm "$CSV_PATH"
	touch "$CSV_PATH"
fi
echo " DECOM , DIM , K , TAG ,% Total,  C#0  ,  C#1  ,  C#10 ,  C#-1" > "$CSV_PATH"

# Tokenise input
python3 core/process.py

rm data/cluster/*

rm data/hasher/*

# Batch train for SVD
python3 core/textprocess.py --decom SVD --dim 512 --tagdim 16
#python3 core/requeue.py

# Batch train for LDA
# python3 core/textprocess.py --decom LDA --tagdim 16
# python3 core/requeue.py
